[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dated_complete_tree"
version = "0.0.1"
authors = [
    {name = "Jonathan David Duke"},
]
description = "Resolve polytomies and interpolate dates for the Open Tree of Life."
requires-python = ">=3.9"
license = {text = "BSD-3-Clause"}
# Runtime dependencies of the dated_complete_tree package itself.
dependencies = [
    "numpy",
    "ete3",
    "ete4",
    "PyQt6",
    "chronosynth",
]

[tool.setuptools]
packages = ["dated_complete_tree"]
