[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dated_complete_tree"
version = "0.0.1"
authors = [
    {name = "Jonathan David Duke"},
]
description = "Interpolate missing dates on phylogenetic trees with no branch lengths. Illustrate using the Open Tree of Life, applying algorithms to resolve its polytomies."
requires-python = ">=3.9"
license = {text = "BSD-3-Clause"}
# Runtime dependencies of the dated_complete_tree package itself.
dependencies = [
    "numpy",
    "ete4"
]

[tool.setuptools]
packages = ["dated_complete_tree"]
include-package-data = true

[tool.setuptools.package-data]
dated_complete_tree = ["config/*.csv"]
